/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115278-ga7e506fcd8-20240519"
#endif /* AVUTIL_FFVERSION_H */
